import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FolderGit2,
  Download,
  Check,
  Box,
  Terminal,
  Code2,
  Copy,
  FileCode,
  CheckCheck,
} from 'lucide-react';
import { BuildSequence } from './BuildSequence';
import { getDownloadScaffoldUrl, previewScaffold } from '../../services/api';
import { Project } from '../../types';

interface Step {
  id: string;
  label: string;
  status: 'pending' | 'running' | 'completed';
}

interface Props {
  project: Project | null;
}

export const ZippingFolder3D: React.FC<Props> = ({ project }) => {
  const [isBuilding, setIsBuilding] = useState(false);
  const [buildComplete, setBuildComplete] = useState(false);
  const [activeFilePath, setActiveFilePath] = useState<string>('backend/app/routers/mock_routes.py');
  const [copied, setCopied] = useState(false);
  const [previewData, setPreviewData] = useState<any>(null);

  useEffect(() => {
    if (project?.id) {
      previewScaffold(project.id)
        .then((data) => {
          setPreviewData(data);
          if (data.files && data.files.length > 0) {
            setActiveFilePath(data.files[0].path);
          }
        })
        .catch((err) => console.error('Failed to preview scaffold:', err));
    }
  }, [project?.id]);

  const [steps, setSteps] = useState<Step[]>([
    { id: '1', label: 'FastAPI App Factory & Middleware', status: 'completed' },
    { id: '2', label: 'Synthesized Mock Endpoints from Roadmap', status: 'completed' },
    { id: '3', label: 'React 18 + Vite + Tailwind Client Shell', status: 'completed' },
    { id: '4', label: 'Multi-stage Dockerfile & docker-compose.yml', status: 'completed' },
    { id: '5', label: 'GitHub Actions CI/CD Verification Workflow', status: 'completed' },
    { id: '6', label: 'In-memory ZIP archive streaming', status: 'completed' },
  ]);

  const handleStartScaffolding = async () => {
    if (!project || isBuilding) return;

    setIsBuilding(true);
    setBuildComplete(false);

    try {
      const data = await previewScaffold(project.id);
      setPreviewData(data);
    } catch (err) {
      console.error('Error fetching scaffold preview:', err);
    }

    setSteps((prev) => prev.map((s) => ({ ...s, status: 'completed' })));
    setIsBuilding(false);
    setBuildComplete(true);

    // Trigger real download immediately
    const downloadUrl = getDownloadScaffoldUrl(project.id);
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.setAttribute('download', `${project.title.toLowerCase().replace(/\s+/g, '_')}_scaffold.zip`);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  if (!project) {
    return (
      <div className="glass-panel p-12 rounded-2xl text-center space-y-4 max-w-xl mx-auto border border-white/10 bg-zinc-950/60">
        <div className="w-12 h-12 rounded-xl bg-zinc-900 border border-white/10 flex items-center justify-center mx-auto">
          <Box className="w-6 h-6 text-zinc-400" />
        </div>
        <h3 className="text-lg font-bold text-white font-sans">No Active Project Roadmap</h3>
        <p className="text-xs text-zinc-400 font-mono">
          Run the AI Decomposer to break down an idea before generating the repository.
        </p>
      </div>
    );
  }

  const getFileLanguage = (path: string): string => {
    if (path.endsWith('.py')) return 'Python';
    if (path.endsWith('.tsx') || path.endsWith('.ts')) return 'TypeScript';
    if (path.endsWith('.json')) return 'JSON';
    if (path.endsWith('.yml') || path.endsWith('.yaml')) return 'YAML';
    if (path.endsWith('.html')) return 'HTML';
    if (path.endsWith('.css')) return 'CSS';
    if (path.endsWith('.js')) return 'JavaScript';
    if (path.endsWith('Dockerfile') || path.includes('Dockerfile')) return 'Dockerfile';
    if (path.endsWith('.md')) return 'Markdown';
    return 'Text';
  };

  // Synthesize dynamic file contents for code inspector
  const getFileContent = (path: string): string => {
    // 1. Primary: Use genuine file content returned by the backend preview API
    const backendFile = previewData?.files?.find((f: any) => f.path === path);
    if (backendFile?.content) {
      return backendFile.content;
    }

    // 2. Fallback: Return accurate, complete template code for each specific file
    if (path === 'backend/app/main.py') {
      return `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routers import mock_routes

app = FastAPI(
    title="${project.title} API",
    description="Generated by Daedalus AI Scaffolding Engine",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(mock_routes.router, prefix="/api/v1", tags=["Roadmap Endpoints"])

@app.get("/")
def read_root():
    return {"system": "${project.title}", "status": "running", "engine": "Daedalus AI"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}
`;
    }

    if (path === 'backend/app/routers/mock_routes.py') {
      const taskRoutes = (project.tasks || [])
        .filter((t) => t.api_route_spec)
        .map((t) => {
          const spec = t.api_route_spec!;
          const method = (spec.method || 'GET').toLowerCase();
          const cleanPath = spec.path || `/mock/${t.task_code.toLowerCase()}`;
          const responsePayload = JSON.stringify(spec.response_mock || { status: 'success', task: t.task_code }, null, 4);
          return `@router.${method}("${cleanPath}", summary="${spec.summary || t.title}")
async def mock_${t.task_code.toLowerCase().replace(/[^a-z0-9]/g, '_')}():
    """Auto-generated mock endpoint for task ${t.task_code}"""
    return ${responsePayload}
`;
        })
        .join('\n');

      return `from fastapi import APIRouter

router = APIRouter()

${taskRoutes || '# No explicit API contracts synthesized for this domain'}
`;
    }

    if (path === 'backend/requirements.txt') {
      return `fastapi>=0.111.0
uvicorn[standard]>=0.30.0
pydantic>=2.7.0
sqlalchemy>=2.0.30
asyncpg>=0.29.0
python-multipart>=0.0.9
httpx>=0.27.0
pytest>=8.0.0
`;
    }

    if (path === 'backend/Dockerfile') {
      return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
    }

    if (path === 'backend/tests/test_main.py') {
      return `from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def test_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json()["status"] == "running"

def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"
`;
    }

    if (path === 'frontend/package.json') {
      return `{
  "name": "frontend",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "lucide-react": "^0.395.0"
  },
  "devDependencies": {
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.4.5",
    "vite": "^5.3.0"
  }
}
`;
    }

    if (path === 'frontend/vite.config.ts') {
      return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true
      }
    }
  }
})
`;
    }

    if (path === 'frontend/index.html') {
      return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${project.title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
    }

    if (path === 'frontend/tsconfig.json') {
      return `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
`;
    }

    if (path === 'frontend/tailwind.config.js') {
      return `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
    }

    if (path === 'frontend/postcss.config.js') {
      return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
    }

    if (path === 'frontend/src/App.tsx') {
      return `import React, { useEffect, useState } from 'react';

export function App() {
  const [data, setData] = useState<any>(null);

  useEffect(() => {
    fetch('/api/v1/health')
      .then(res => res.json())
      .then(d => setData(d))
      .catch(err => console.error(err));
  }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-white flex flex-col items-center justify-center p-6">
      <div className="p-8 rounded-2xl border border-cyan-500/20 bg-slate-900/50 backdrop-blur-md max-w-xl text-center shadow-2xl">
        <h1 className="text-4xl font-bold tracking-tight bg-gradient-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">
          ${project.title}
        </h1>
        <p className="mt-4 text-slate-400">
          Scaffolded by Daedalus AI. FastAPI backend & mock APIs ready.
        </p>
        <div className="mt-6 p-4 rounded-lg bg-black/40 text-left font-mono text-xs text-cyan-300">
          Status: {data ? JSON.stringify(data) : 'Connecting to API...'}
        </div>
      </div>
    </div>
  );
}

export default App;
`;
    }

    if (path === 'frontend/src/main.tsx') {
      return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
`;
    }

    if (path === 'frontend/src/index.css') {
      return `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  background-color: #0B0F19;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
`;
    }

    if (path === 'frontend/Dockerfile') {
      return `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
    }

    if (path === 'docker-compose.yml') {
      return `version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: app_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/app_db
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
`;
    }

    if (path === 'README.md') {
      return `# ${project.title}

> Generated automatically by **Daedalus AI** — Autonomous Multi-Agent Orchestration.

## Architecture Overview
- **Backend**: FastAPI (Python 3.12)
- **Frontend**: React + Vite + Tailwind CSS
- **Database**: PostgreSQL with pgvector
- **Infrastructure**: Docker & Docker Compose
- **CI/CD**: GitHub Actions

## Quickstart with Docker Compose

\`\`\`bash
docker compose up --build
\`\`\`
- Frontend: http://localhost:3000
- Backend: http://localhost:8000
- API Docs (Swagger): http://localhost:8000/docs
`;
    }

    return `name: CI / CD Verification Pipeline

on:
  push:
    branches: [ main, dev, 'task/**' ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Run Pytest
        run: |
          cd backend
          pytest tests/
`;
  };

  const manifestFiles = (previewData?.files && previewData.files.length > 0)
    ? previewData.files.map((f: any) => ({ path: f.path, type: f.type, desc: f.description }))
    : [
        { path: 'backend/app/main.py', type: 'backend', desc: 'FastAPI App factory & CORS' },
        { path: 'backend/app/routers/mock_routes.py', type: 'backend', desc: 'Synthesized Mock Endpoints' },
        { path: 'backend/requirements.txt', type: 'backend', desc: 'Pinned Python dependencies' },
        { path: 'backend/Dockerfile', type: 'docker', desc: 'Python 3.12 container' },
        { path: 'frontend/src/App.tsx', type: 'frontend', desc: 'React 18 client shell' },
        { path: 'frontend/package.json', type: 'frontend', desc: 'Dependencies & scripts' },
        { path: 'docker-compose.yml', type: 'config', desc: 'PostgreSQL + Backend + Frontend' },
        { path: '.github/workflows/ci.yml', type: 'ci', desc: 'Pytest & linting gate' },
        { path: 'README.md', type: 'docs', desc: 'Project architecture & instructions' },
      ];

  const currentContent = getFileContent(activeFilePath);

  const handleCopyCode = () => {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6">
      {/* Hero Action Card */}
      <div className="glass-panel rounded-2xl p-8 border border-white/10 text-center relative overflow-hidden bg-zinc-950/60 space-y-5">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-zinc-300 text-xs font-mono">
          <Terminal className="w-3.5 h-3.5 text-zinc-400" />
          <span>INSTANT STARTER REPOSITORY SYNTHESIZER</span>
        </div>

        <div className="space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white font-sans">
            Ready to Scaffold <span className="text-zinc-200">"{project.title}"</span>
          </h2>
          <p className="text-xs sm:text-sm text-zinc-400 max-w-lg mx-auto leading-relaxed font-sans">
            Synthesizes a runnable full-stack codebase with FastAPI routes, React state,
            Docker orchestration, and automated CI tests.
          </p>
        </div>

        {/* Action Button */}
        <div className="pt-2 flex justify-center">
          <button
            onClick={handleStartScaffolding}
            disabled={isBuilding}
            className="px-6 py-3 rounded-xl bg-white hover:bg-zinc-200 text-zinc-950 font-sans text-xs font-bold tracking-wide flex items-center gap-2.5 cursor-pointer transition-all shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FolderGit2 className="w-4 h-4 text-zinc-950" />
            <span>{isBuilding ? 'Synthesizing Architecture...' : 'Generate Repository (.zip)'}</span>
          </button>
        </div>
      </div>

      {/* Manifest File Tree & Live Code Inspector */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 items-start">
        {/* Left: File Picker */}
        <div className="lg:col-span-5 glass-panel rounded-2xl p-4 border border-white/10 space-y-2.5 bg-zinc-950/60">
          <div className="flex items-center justify-between pb-2 border-b border-white/5">
            <span className="text-xs font-mono font-bold text-zinc-300">
              SYNTHESIZED_MANIFEST
            </span>
            <span className="text-[10px] font-mono text-zinc-500">
              {manifestFiles.length} files in repository
            </span>
          </div>

          <div className="space-y-1.5 max-h-[460px] overflow-y-auto pr-1">
            {manifestFiles.map((file, idx) => {
              const isActive = activeFilePath === file.path;
              return (
                <button
                  key={idx}
                  type="button"
                  onClick={() => setActiveFilePath(file.path)}
                  className={`w-full text-left p-2.5 rounded-xl border transition-all cursor-pointer font-mono text-xs flex flex-col gap-1 ${
                    isActive
                      ? 'bg-zinc-900 border-cyan-500/50 shadow-sm text-white'
                      : 'bg-zinc-900/40 border-white/5 hover:border-white/15 hover:bg-zinc-900/70 text-zinc-400'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className={`font-bold truncate max-w-[200px] ${isActive ? 'text-cyan-300' : 'text-zinc-200'}`}>
                      {file.path}
                    </span>
                    <span className="text-[9px] text-zinc-400 bg-white/5 px-1.5 py-0.5 rounded">
                      {file.type}
                    </span>
                  </div>
                  <span className="text-[11px] text-zinc-500 font-sans truncate">
                    {file.desc}
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Right: Live Code Inspector */}
        <div className="lg:col-span-7 glass-panel rounded-2xl overflow-hidden border border-white/10 bg-zinc-950 flex flex-col h-[460px]">
          {/* Header Bar */}
          <div className="bg-zinc-900 px-4 py-2.5 border-b border-white/10 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileCode className="w-3.5 h-3.5 text-cyan-400" />
              <span className="text-xs font-mono text-zinc-200 font-semibold truncate max-w-[200px]">
                {activeFilePath}
              </span>
              <span className="text-[10px] font-mono text-zinc-400 px-1.5 py-0.5 rounded bg-white/5 border border-white/10">
                {getFileLanguage(activeFilePath)}
              </span>
              <span className="text-[10px] font-mono text-zinc-500 hidden sm:inline">
                {currentContent.split('\n').length} lines
              </span>
            </div>
            <button
              onClick={handleCopyCode}
              className="px-2.5 py-1 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-[11px] font-mono flex items-center gap-1.5 border border-white/10 transition-colors cursor-pointer"
            >
              {copied ? (
                <>
                  <CheckCheck className="w-3 h-3 text-emerald-400" />
                  <span className="text-emerald-400">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="w-3 h-3" />
                  <span>Copy Code</span>
                </>
              )}
            </button>
          </div>

          {/* Code Viewer Body */}
          <pre className="flex-1 p-4 font-mono text-xs text-zinc-300 overflow-y-auto overflow-x-auto leading-relaxed select-text bg-zinc-950/90">
            {currentContent}
          </pre>
        </div>
      </div>

      {/* Cascading Build Sequence */}
      {(isBuilding || buildComplete) && (
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-panel rounded-2xl p-6 border border-white/10 space-y-4 bg-zinc-950/80"
        >
          <div className="flex items-center justify-between pb-2 border-b border-white/10">
            <span className="text-xs font-mono text-zinc-300 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-zinc-400" />
              BUILD_PIPELINE_OUTPUT
            </span>
            <span className="text-[11px] font-mono text-zinc-400">
              Target: InMemory Buffer &gt; ZIP
            </span>
          </div>

          <BuildSequence steps={steps} />
        </motion.div>
      )}

      {/* Download Completion Card */}
      <AnimatePresence>
        {buildComplete && (
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            className="glass-panel p-6 rounded-2xl border border-emerald-500/30 text-center space-y-3 bg-zinc-950/90"
          >
            <div className="w-12 h-12 mx-auto rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
              <Check className="w-6 h-6 text-emerald-400" />
            </div>

            <div className="space-y-1">
              <h4 className="text-base font-bold text-white font-sans">
                Repository Packaged & Download Initiated
              </h4>
              <p className="text-xs font-mono text-zinc-400">
                Run <code className="text-zinc-200 bg-zinc-900 px-1.5 py-0.5 rounded border border-white/10">docker compose up --build</code> to start your sprint environment.
              </p>
            </div>

            <div className="pt-2">
              <a
                href={getDownloadScaffoldUrl(project.id)}
                download={`${project.title.toLowerCase().replace(/\s+/g, '_')}_scaffold.zip`}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-zinc-900 border border-white/10 text-xs font-mono text-zinc-300 hover:text-white hover:border-white/25 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                Click to re-download ZIP archive
              </a>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
